interface CFCallableBase {
  /**
   * Origin of the request. Can be either 'web' or 'wrapper'.
   */
  origin: 'web' | 'wrapper';
  /**
   * Unique random client id generated by the wrapper application.
   * Unique client id generated by the wrapper application.
   * E.g., 'HOSTNAME::IPv4PRIVATE::RANDOMNUMBER'
   */
  clientId: string;
}

export type { CFCallableBase };
