export const paths = {
  // pdf, doc, docx, docm, dotx, dot, pptx, xls, xlsx, csv
  pdf: [
    'C:\\Program Files\\Adobe\\Acrobat DC\\Acrobat\\Acrobat.exe',
    'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
    'C:\\Program Files\\Mozilla Firefox',
  ],
  doc: ['C:Program FilesMicrosoft Office\rootOffice16WINWORD.EXE'],
  docx: ['C:Program FilesMicrosoft Office\rootOffice16WINWORD.EXE'],
  docm: ['C:Program FilesMicrosoft Office\rootOffice16WINWORD.EXE'],
  dot: ['C:Program FilesMicrosoft Office\rootOffice16WINWORD.EXE'],
  dotx: ['C:Program FilesMicrosoft Office\rootOffice16WINWORD.EXE'],
  ppt: ['C:Program FilesMicrosoft Office\rootOffice16POWERPNT.EXE'],
  pptx: ['C:Program FilesMicrosoft Office\rootOffice16POWERPNT.EXE'],
  pptm: ['C:Program FilesMicrosoft Office\rootOffice16POWERPNT.EXE'],
  pps: ['C:Program FilesMicrosoft Office\rootOffice16POWERPNT.EXE'],
  ppsx: ['C:Program FilesMicrosoft Office\rootOffice16POWERPNT.EXE'],
  ppsm: ['C:Program FilesMicrosoft Office\rootOffice16POWERPNT.EXE'],
  pot: ['C:Program FilesMicrosoft Office\rootOffice16POWERPNT.EXE'],
  potx: ['C:Program FilesMicrosoft Office\rootOffice16POWERPNT.EXE'],
  potm: ['C:Program FilesMicrosoft Office\rootOffice16POWERPNT.EXE'],
  xl: ['C:Program FilesMicrosoft Office\rootOffice16EXCEL.EXE'],
  xls: ['C:Program FilesMicrosoft Office\rootOffice16EXCEL.EXE'],
  xlsx: ['C:Program FilesMicrosoft Office\rootOffice16EXCEL.EXE'],
  xlsm: ['C:Program FilesMicrosoft Office\rootOffice16EXCEL.EXE'],
  xlsb: ['C:Program FilesMicrosoft Office\rootOffice16EXCEL.EXE'],
  xlam: ['C:Program FilesMicrosoft Office\rootOffice16EXCEL.EXE'],
  xltx: ['C:Program FilesMicrosoft Office\rootOffice16EXCEL.EXE'],
  xlt: ['C:Program FilesMicrosoft Office\rootOffice16EXCEL.EXE'],
  xla: ['C:Program FilesMicrosoft Office\rootOffice16EXCEL.EXE'],
  xlm: ['C:Program FilesMicrosoft Office\rootOffice16EXCEL.EXE'],
  xlw: ['C:Program FilesMicrosoft Office\rootOffice16EXCEL.EXE'],
};
