export const paths = {
  // pdf, doc, docx, docm, dotx, dot, pptx, xls, xlsx, csv
  pdf: [
    'C:\\Program Files\\Adobe\\Acrobat DC\\Acrobat\\Acrobat.exe',
    'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
    'C:\\Program Files\\Mozilla Firefox',
  ],
  doc: ['C:\\Program Files\\Microsoft Office\\root\\Office16\\WINWORD.EXE'],
  docx: ['C:\\Program Files\\Microsoft Office\\root\\Office16\\WINWORD.EXE'],
  docm: ['C:\\Program Files\\Microsoft Office\\root\\Office16\\WINWORD.EXE'],
  dotx: ['C:\\Program Files\\Microsoft Office\\root\\Office16\\WINWORD.EXE'],
  dot: ['C:\\Program Files\\Microsoft Office\\root\\Office16\\WINWORD.EXE'],
  ppt: ['C:\\Program Files\\Microsoft Office\\root\\Office16\\POWERPNT.EXE'],
  pptx: ['C:\\Program Files\\Microsoft Office\\root\\Office16\\POWERPNT.EXE'],
  pptm: ['C:\\Program Files\\Microsoft Office\\root\\Office16\\POWERPNT.EXE'],
  pps: ['C:\\Program Files\\Microsoft Office\\root\\Office16\\POWERPNT.EXE'],
  ppsx: ['C:\\Program Files\\Microsoft Office\\root\\Office16\\POWERPNT.EXE'],
  ppsm: ['C:\\Program Files\\Microsoft Office\\root\\Office16\\POWERPNT.EXE'],
  pot: ['C:\\Program Files\\Microsoft Office\\root\\Office16\\POWERPNT.EXE'],
  potx: ['C:\\Program Files\\Microsoft Office\\root\\Office16\\POWERPNT.EXE'],
  potm: ['C:\\Program Files\\Microsoft Office\\root\\Office16\\POWERPNT.EXE'],
  xl: ['C:\\Program Files\\Microsoft Office\\root\\Office16\\EXCEL.EXE'],
  xls: ['C:\\Program Files\\Microsoft Office\\root\\Office16\\EXCEL.EXE'],
  csv: ['C:\\Program Files\\Microsoft Office\\root\\Office16\\EXCEL.EXE'],
  tsv: ['C:\\Program Files\\Microsoft Office\\root\\Office16\\EXCEL.EXE'],
  xlsx: ['C:\\Program Files\\Microsoft Office\\root\\Office16\\EXCEL.EXE'],
  xlsm: ['C:\\Program Files\\Microsoft Office\\root\\Office16\\EXCEL.EXE'],
  xlsb: ['C:\\Program Files\\Microsoft Office\\root\\Office16\\EXCEL.EXE'],
  xlam: ['C:\\Program Files\\Microsoft Office\\root\\Office16\\EXCEL.EXE'],
  xltx: ['C:\\Program Files\\Microsoft Office\\root\\Office16\\EXCEL.EXE'],
  xlt: ['C:\\Program Files\\Microsoft Office\\root\\Office16\\EXCEL.EXE'],
  xla: ['C:\\Program Files\\Microsoft Office\\root\\Office16\\EXCEL.EXE'],
  xlm: ['C:\\Program Files\\Microsoft Office\\root\\Office16\\EXCEL.EXE'],
  xlw: ['C:\\Program Files\\Microsoft Office\\root\\Office16\\EXCEL.EXE'],
  css: ['C:\\Windows\\System32\\notepad.exe'],
  txt: ['C:\\Windows\\System32\\notepad.exe'],
  htm: ['C:\\Windows\\System32\\notepad.exe'],
  html: ['C:\\Windows\\System32\\notepad.exe'],
  shtml: ['C:\\Windows\\System32\\notepad.exe'],
  shtm: ['C:\\Windows\\System32\\notepad.exe'],
  xhtml: ['C:\\Windows\\System32\\notepad.exe'],
  js: ['C:\\Windows\\System32\\notepad.exe'],
  json: ['C:\\Windows\\System32\\notepad.exe'],
  jsonl: ['C:\\Windows\\System32\\notepad.exe'],
  php: ['C:\\Windows\\System32\\notepad.exe'],
  phtml: ['C:\\Windows\\System32\\notepad.exe'],
  pht: ['C:\\Windows\\System32\\notepad.exe'],
  py: ['C:\\Windows\\System32\\notepad.exe'],
  wml: ['C:\\Windows\\System32\\notepad.exe'],
  xml: ['C:\\Windows\\System32\\notepad.exe'],
  xsd: ['C:\\Windows\\System32\\notepad.exe'],
};
