#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\)): .{1,}$"; then
  echo "husky:git:commit-msg: Commit aborted. Your commit message is invalid." >&2
  echo "husky:git:commit-msg: " >&2
  echo "husky:git:commit-msg: Please follow the convention below:" >&2
  echo "husky:git:commit-msg:   <type>(scope): <description>" >&2
  echo "husky:git:commit-msg:   [optional body]" >&2
  echo "husky:git:commit-msg:   [optional footer(s)]" >&2
  echo "husky:git:commit-msg: " >&2
  echo "husky:git:commit-msg: For example:" >&2
  echo "husky:git:commit-msg:   feat(functions-gcp): add auth blocking function" >&2
  echo "husky:git:commit-msg: " >&2
  exit 1
fi

if ! head -1 "$1" | grep -qE "^.{1,72}$"; then
  echo "husky:git:commit-msg: Commit aborted. Your commit message is too long." >&2
  echo "husky:git:commit-msg: Please limit your commit messages to 72 characters long." >&2
  echo "husky:git:commit-msg: " >&2
  exit 1
fi
